### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by wd308389182** [Mr-Cai/tencent_ad#22]
启动项目的Dome后， 点击广告出现
I/tencent.ad(18673): Rejecting re-init on previously-failed class java.lang.Class<com.qq.e.comm.plugin.POFactoryImpl>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/base.apk"],nativeLibraryDirectories=[/data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/lib/x86, /data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libyaqcore_gdtadv.so"
I/tencent.ad(18673): (Throwable with no stack trace)
I/tencent.ad(18673): 
E/gdt_ad_mob(18673): Fail to init splash plugin
E/gdt_ad_mob(18673): com.qq.e.comm.managers.plugin.a: Fail to getfactory implement instance for interface:com.qq.e.comm.pi.POFactory
E/gdt_ad_mob(18673): 	at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:157)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2)
E/gdt_ad_mob(18673): 	at com.qq.e.ads.splash.SplashAD$1.run(Unknown Source:22)
E/gdt_ad_mob(18673): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/gdt_ad_mob(18673): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/gdt_ad_mob(18673): 	at java.lang.Thread.run(Thread.java:919)
E/gdt_ad_mob(18673): Caused by: java.lang.NoClassDefFoundError: com.qq.e.comm.plugin.POFactoryImpl
E/gdt_ad_mob(18673): 	at java.lang.reflect.Method.invoke(Native Method)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:86)
E/gdt_ad_mob(18673): 	... 5 more
E/gdt_ad_mob(18673): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/base.apk"],nativeLibraryDirectories=[/data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/lib/x86, /data/app/tencent.ad-FkOSHL_4EQhvRoZH9p6ybA==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libyaqcore_gdtadv.so"
E/gdt_ad_mob(18673): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/gdt_ad_mob(18673): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/gdt_ad_mob(18673): 	at java.lang.System.loadLibrary(System.java:1667)
E/gdt_ad_mob(18673): 	at yaq.gdtadv.<clinit>(Unknown Source:103)
E/gdt_ad_mob(18673): 	at yaq.gdtadv.getobjresult(Native Method)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.plugin.x.a.a(Unknown Source:6)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.plugin.POFactoryImpl.<init>(Unknown Source:3)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.plugin.POFactoryImpl.<clinit>(Unknown Source:2)
E/gdt_ad_mob(18673): 	at java.lang.reflect.Method.invoke(Native Method)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.managers.plugin.PM.getFactory(Unknown Source:86)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.managers.plugin.PM.getPOFactory(Unknown Source:2)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.services.a$1.onResponse(Unknown Source:123)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:98)
E/gdt_ad_mob(18673): 	at com.qq.e.comm.net.NetworkClientImpl$TaskCallable.call(Unknown Source:0)
E/gdt_ad_mob(18673): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/gdt_ad_mob(18673): 	... 3 more
D/EGL_emulation(18673): eglMakeCurrent: 0xe8655080: ver 3 0 (tinfo 0xdd068490)
I/腾讯广告调试日志(18673): SplashAD onNoAD: 无广告 错误码:2001 初始化错误，详细码：200

**Comment by yy1300326388** [comment]
我使用的这个[flutter_qq_ads](https://github.com/FlutterAds/flutter_qq_ads)插件，非常不错，支持 Android、iOS
[
![image](https://user-images.githubusercontent.com/8764899/131288138-c54de4cd-6f2f-4833-b16c-0f4a3b007836.png)
](https://github.com/FlutterAds/flutter_qq_ads)
